### ISSUE TITLE
Support hoppers

### ISSUE THREAD

**Issue by tacotexmex** [joe7575/Minetest-Tubelib#1]
Would be cool to see integrated hopper support. See hopper's [api.txt](https://github.com/minetest-mods/hopper/blob/master/api.txt)

**Comment by joe7575** [comment]
How shall this work?
Tubelib and Hopper are competing mods, both are moving items around.
Both Tubelib and Hopper have APIs, to register items with inventories.
The connecting element between both are chests or other supported nodes with inventories.

**Comment by tacotexmex** [comment]
All this is true of course, and perhaps I've overlooked this item, but I cannot find a way to drop an **item directly from player to tube** (without having to move it to a chest first). In pipeworks I believe this item is called somethinglike a _vacuum pipe_, but a more elegant solution would be a funnel-like one, such as the hopper. That's why I created the issue.

**Comment by joe7575** [comment]
Ok, I got it.
It seams to be easier to add a funnel to tubelib than bringing both mods together.
I will try something...

**Comment by joe7575** [comment]
Funnel added. Give it a try.
Please note: As for all inventory nodes, you need a Tubelib Pusher in addition to send items through tubes.

**Comment by tacotexmex** [comment]
Works excellent, thanks!
