### ISSUE TITLE
New feature:

### ISSUE THREAD

**Issue by piecubed** [joe7575/Minetest-Tubelib#4]
What if you made teleboxes?  They work kinds like teleporting tubes in Technic...  It really annoying, because you have to make the tube go all that way, and impractical...

**Comment by joe7575** [comment]
A Teleporter node is now available as part of TechPack for testing.

**Comment by piecubed** [comment]
Can you work on the bugs?  There is still quite a lot with them...

**Comment by joe7575** [comment]
There are no known open bugs. Could you explain more in detail?

**Comment by piecubed** [comment]
Talk to billyS.  He had to shutdown his server temporarily because of them.

**Comment by joe7575** [comment]
I talked with him, but without any result.
TechPack is running on my own Server since month without issues.

**Comment by piecubed** [comment]
Huh, ill look on my server then.
